<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jenkins" nsURI="http://www.example.org/jenkins" nsPrefix="jenkins">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastFailure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodemanagement" eType="#//SourceCodeManagement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postbuild" eType="#//PostBuild"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//Trigger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="build" eType="#//Build"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeManagement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//Credential"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteShell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostBuild" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DockerEngine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildAndPulishDockerImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dockerengine" eType="#//DockerEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteShellRemote">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostBuildPlugin" abstract="true" eSuperTypes="#//PostBuild"/>
  <eClassifiers xsi:type="ecore:EClass" name="Jenkins">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//Config"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeline" upperBound="-1"
        eType="#//Pipeline" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" upperBound="-1"
        eType="#//Credential" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" upperBound="-1"
        eType="#//Server" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dockerengine" upperBound="-1"
        eType="#//DockerEngine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Build">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildandpulishdockerimage"
        upperBound="-1" eType="#//BuildAndPulishDockerImage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executeshell" upperBound="-1"
        eType="#//ExecuteShell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executeshellremote" upperBound="-1"
        eType="#//ExecuteShellRemote" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
