<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jenkins" nsURI="http://www.example.org/jenkins" nsPrefix="jenkins">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastFailure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcecodemanagement" upperBound="-1"
        eType="#//SourceCodeManagement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="build" upperBound="-1"
        eType="#//Build" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postbuild" upperBound="-1"
        eType="#//PostBuild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeManagement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//Credential"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credential">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" upperBound="-1" eType="#//TriggerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Build" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerType">
    <eLiterals name="PUSH"/>
    <eLiterals name="OPENMR" value="1"/>
    <eLiterals name="CLOSEMR" value="2"/>
    <eLiterals name="ACMR" value="3"/>
    <eLiterals name="COMMENTS" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteShell" eSuperTypes="#//Build">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildPlugin" abstract="true" eSuperTypes="#//Build"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostBuild" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DockerEngine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//Credential"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credential" eType="#//Credential"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildAndPulishDockerImage" eSuperTypes="#//BuildPlugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dockerengine" eType="#//DockerEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecuteShellRemote" eSuperTypes="#//BuildPlugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PostBuildPlugin" abstract="true" eSuperTypes="#//PostBuild"/>
</ecore:EPackage>
